name: Improve documentation
description: Propose improvements or report problems in the guideline.
labels: ["state:needs triage"]
body:
  - type: checkboxes
    attributes:
      label: Before opening an issue
      description: Please review the following checklist before submitting.
      options:
        - label: I have searched existing issues (open and closed) and did not find a duplicate.
          required: true

  - type: dropdown
    attributes:
      label: Issue type
      description: |
        - Suggestion — Content updates (translations, wording tweaks; include where and a short example)
        - Proposal — Changes to the guideline itself (purpose, detailed change, and impact)
        - Report — Problems in the guideline (unclear wording, outdated content, broken links)
      options:
        - Suggestion
        - Proposal
        - Report
    validations:
      required: true

  - type: textarea
    attributes:
      label: As Is
      description: Describe the current state and known problems.
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Be
      description: Describe the desired state; include acceptance criteria and impact.
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Do
      description: List concrete tasks to implement the improvement (owner and deadline optional).
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional information
      description: |
        - Can you reproduce the issue reliably? How often does it occur and who is affected?
        - Provide any relevant context, examples, or screenshots.
        - Link to related guideline sections or external references if applicable.
    validations:
      required: false
